### PR TITLE
SamsungBCMRIL: update for new RIL

### PR DESCRIPTION
**Pull request by xenon92**
Reflects changes with respect to the updated RIL.java

### CODE REVIEW

**Comment by pawitp** [comment]
+1

I'll probably wait until M4 is out before merging it since that'll probably use the old RIL.

**Comment by xenon92** [comment]
Alright.

For others who are following the commits and this repo, you'll have to use this patch as most other ROMs that derive from CM have updated to the new RIL.java. (They'll probably revert to the old RIL if CM decides to revert too, as pawitp is saying).

Until that happens, your builds will break till you apply this commit.

https://github.com/xenon92/android_device_samsung_i9082/commit/d57e8928c45615c5c78dbc58639ce1de0f45e9a1

**Comment by pawitp** [comment]
CM's not reverting, it's just that M-builds are generated from a slightly different branch that doesn't contain bleeding-edge code.

**Comment by pawitp** [comment]
Merged

**Pull request closed without merging**
