### PR TITLE
Fix button feedback

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by pawitp** [comment]
Thank you for submitting a patch.

Can you please describe the problem and how you got these new values?

**Comment by luk1337** [comment]
Actually sec_touchkey.kl maps our (s2vep,s2ve,i9082) menu and back key as VIRTUAL so it fixes haptic vibration on this keys. But it works only when "overlay/frameworks/base/core/res/res/values/config.xml" have patterns for touching a virtual key.
I copied this lines from i9100 repository and this works on my Galaxy S2 Plus so it should work on i9082 too.

**Comment by xenon92** [comment]
config_virtualKeyVibePattern
config_keyboardTapVibePattern

Only these two configs are being overridden here. Other values are exactly the same as in in the base config.xml. Linked below.

https://github.com/CyanogenMod/android_frameworks_base/blob/cm-11.0/core/res/res/values/config.xml#L531

https://github.com/CyanogenMod/android_frameworks_base/blob/cm-11.0/core/res/res/values/config.xml#L552

https://github.com/CyanogenMod/android_frameworks_base/blob/cm-11.0/core/res/res/values/config.xml#L560

https://github.com/CyanogenMod/android_frameworks_base/blob/cm-11.0/core/res/res/values/config.xml#L560

Issue: The default behavior of softkeys on stock ROM is to provide haptic
vibration on touch. In AOSP based ROMs, this behavior is lost.

This works - https://gist.github.com/xenon92/af8df0708c39a24a9dc5
ROM - http://forum.xda-developers.com/galaxy-grand-duos/development/rom-cyanogenmod-11-t2827007

As far as this commit goes, I'll have to build and test if over-riding those (two) values fix the soft key vibrations from the device tree itself without the need to add a patch to frameworks/base. 

I am closing the pull request on my device tree. I'll pull your patch from here after I test it myself, or pawitp tests it.

**Comment by pawitp** [comment]
I'll look at it around the middle of August, when I'm back in Thailand.

**Comment by pawitp** [comment]
https://github.com/pawitp/android_device_samsung_i9082/commit/1580bc929ba424910e5ff5d03b563e9589567c2b is the proper fix.

**Comment by pawitp** [comment]
Oops... make that https://github.com/pawitp/android_device_samsung_i9082/commit/b3411c2e495f886bfd77de0480c0b1bd2d68ff13

**Pull request closed without merging**
